name: CI Pipeline

on:
  push:
    branches: [intern_loca]
  pull_request:
    branches: [intern_loca]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./nest

      - name: Run Backend Tests
        run: npm test
        working-directory: ./nest

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        run: npm install --force
        working-directory: ./angular-login

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./angular-login
